=== crankycoder/mozilla-pipeline-schemas/schemas/telemetry/sync/sync.4.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "additionalProperties": false,
  "description": "Schema for sync pings as sent by this code: https://searchfox.org/mozilla-central/rev/ee40541496d3ad738097eebadaf4965ca1343b7a/services/sync/modules/telemetry.js#490 and documented at https://firefox-source-docs.mozilla.org/toolkit/components/telemetry/telemetry/data/sync-ping.html",
  "properties": {
    "application": {
      "additionalProperties": false,
      "properties": {
        "architecture": {
          "type": "string"
        },
        "buildId": {
          "pattern": "^[0-9]{10}",
          "type": "string"
        },
        "channel": {
          "type": "string"
        },
        "displayVersion": {
          "pattern": "^[0-9]{2,3}\\.",
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "platformVersion": {
          "pattern": "^[0-9]{2,3}\\.",
          "type": "string"
        },
        "vendor": {
          "type": "string"
        },
        "version": {
          "pattern": "^[0-9]{2,3}\\.",
          "type": "string"
        },
        "xpcomAbi": {
          "type": "string"
        }
      },
      "required": [
        "architecture",
        "buildId",
        "channel",
        "name",
        "platformVersion",
        "version",
        "vendor",
        "xpcomAbi"
      ],
      "type": "object"
    },
    "creationDate": {
      "pattern": "^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}\\.[0-9]{3}Z$",
      "type": "string"
    },
    "id": {
      "pattern": "^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$",
      "type": "string"
    },
    "payload": {
      "properties": {
        "deviceID": {
          "description": "Hashed FxA Device ID, hex string of 64 characters, not included if the user is not logged in. If this changes between syncs, the payload is submitted.",
          "type": "string"
        },
        "discarded": {
          "description": "Number of syncs discarded -- left out if zero.",
          "type": "integer"
        },
        "events": {
          "items": {
            "items": [
              {
                "minimum": 0,
                "type": "integer"
              },
              {
                "type": "string"
              },
              {
                "type": "string"
              },
              {
                "type": "string"
              },
              {
                "type": [
                  "string",
                  "null"
                ]
              },
              {
                "additionalProperties": {
                  "type": [
                    "string",
                    "null"
                  ]
                },
                "type": [
                  "object",
                  "null"
                ]
              }
            ],
            "maxItems": 6,
            "minItems": 4,
            "type": "array"
          },
          "type": "array"
        },
        "histograms": {
          "additionalProperties": {
            "additionalProperties": false,
            "properties": {
              "bucket_count": {
                "minimum": 0,
                "type": "integer"
              },
              "histogram_type": {
                "minimum": 0,
                "type": "integer"
              },
              "log_sum": {
                "minimum": 0,
                "type": "number"
              },
              "log_sum_squares": {
                "minimum": 0,
                "type": "number"
              },
              "range": {
                "type": "array"
              },
              "sum": {
                "minimum": 0,
                "type": "integer"
              },
              "sum_squares_hi": {
                "minimum": 0,
                "type": "integer"
              },
              "sum_squares_lo": {
                "minimum": 0,
                "type": "integer"
              },
              "values": {
                "additionalProperties": false,
                "patternProperties": {
                  "^[0-9]+$": {
                    "minimum": 0,
                    "type": "integer"
                  }
                },
                "type": "object"
              }
            },
            "type": "object"
          },
          "type": "object"
        },
        "os": {
          "description": "OS data from the current telemetry environment. OS specific, but typically includes name, version and locale.",
          "properties": {
            "locale": {
              "type": "string"
            },
            "name": {
              "type": "string"
            },
            "version": {
              "type": "string"
            }
          },
          "type": "object"
        },
        "sessionStartDate": {
          "description": "Hourly precision, ISO date in local time",
          "format": "date-time",
          "type": "string"
        },
        "syncs": {
          "description": "Array of recorded syncs. The ping is not submitted if this would be empty",
          "items": {
            "properties": {
              "devices": {
                "items": {
                  "properties": {
                    "id": {
                      "description": "Hashed FxA device id for device",
                      "type": "string"
                    },
                    "os": {
                      "description": "OS string as reported by Services.appinfo.OS",
                      "type": "string"
                    },
                    "version": {
                      "description": "Firefox version, as reported by Services.appinfo.version",
                      "type": "string"
                    }
                  },
                  "type": "object"
                },
                "type": "array"
              },
              "didLogin": {
                "description": "Optional, is this the first sync after login? Excluded if we don't know.",
                "type": "boolean"
              },
              "engines": {
                "description": "Information about each engine's sync.",
                "items": {
                  "properties": {
                    "failureReason": {
                      "description": "Optional, excluded if there was no error.",
                      "properties": {
                        "code": {
                          "description": "Only present for httperror and networkerror.",
                          "type": "integer"
                        },
                        "error": {
                          "description": "Only present for othererror and unexpectederror.",
                          "type": "string"
                        },
                        "from": {
                          "description": "Optional, and only present for autherror.",
                          "type": "string"
                        },
                        "name": {
                          "description": "httperror, networkerror, shutdownerror, etc.",
                          "type": "string"
                        }
                      },
                      "type": "object"
                    },
                    "incoming": {
                      "description": "Optional, excluded if all items would be 0. A missing item indicates a value of 0.",
                      "properties": {
                        "applied": {
                          "description": "Number of records applied",
                          "type": "integer"
                        },
                        "failed": {
                          "description": "Number of records that failed to apply",
                          "type": "integer"
                        },
                        "newFailed": {
                          "description": "Number of records that failed for the first time this sync",
                          "type": "integer"
                        },
                        "reconciled": {
                          "description": "Number of records that were reconciled",
                          "type": "integer"
                        },
                        "succeeded": {
                          "description": "Number of records that applied without error",
                          "type": "integer"
                        }
                      },
                      "type": "object"
                    },
                    "name": {
                      "description": "bookmarks, tabs, etc.",
                      "type": "string"
                    },
                    "outgoing": {
                      "description": "Optional, excluded if it would be empty. Records that would be empty (e.g. 0 sent and 0 failed) are omitted.",
                      "items": {
                        "properties": {
                          "failed": {
                            "description": "Number that failed to send. Zero values are omitted.",
                            "type": "integer"
                          },
                          "sent": {
                            "description": "Number of outgoing records sent. Zero values are omitted.",
                            "type": "integer"
                          }
                        },
                        "type": "object"
                      },
                      "type": "array"
                    },
                    "status": {
                      "description": "The value of Status.engines, if it holds a non-success value.",
                      "type": "string"
                    },
                    "took": {
                      "description": "optional duration in milliseconds, values of 0 are omitted.",
                      "type": "integer"
                    },
                    "validation": {
                      "description": "Optional, excluded if it would be empty or if the engine cannot or did not run validation on itself.",
                      "properties": {
                        "checked": {
                          "type": "integer"
                        },
                        "failureReason": {
                          "description": "Optional, excluded if there was no error.",
                          "properties": {
                            "code": {
                              "description": "Only present for httperror and networkerror.",
                              "type": "integer"
                            },
                            "error": {
                              "description": "Only present for othererror and unexpectederror.",
                              "type": "string"
                            },
                            "from": {
                              "description": "Optional, and only present for autherror.",
                              "type": "string"
                            },
                            "name": {
                              "description": "httperror, networkerror, shutdownerror, etc.",
                              "type": "string"
                            }
                          },
                          "type": "object"
                        },
                        "problems": {
                          "description": "Entries with a count of 0 are excluded, the array is excluded if no problems are found.",
                          "items": {
                            "properties": {
                              "count": {
                                "description": "Number of times it occurred.",
                                "type": "integer"
                              },
                              "name": {
                                "description": "The problem identified.",
                                "type": "string"
                              }
                            },
                            "type": "object"
                          },
                          "type": "array"
                        },
                        "took": {
                          "description": "non-monotonic integer duration in milliseconds",
                          "type": "integer"
                        },
                        "version": {
                          "description": "Optional validator version, default of 0.",
                          "type": "integer"
                        }
                      },
                      "type": "object"
                    }
                  },
                  "type": "object"
                },
                "type": "array"
              },
              "failureReason": {
                "description": "Optional, excluded if there was no error.",
                "properties": {
                  "code": {
                    "description": "Only present for httperror and networkerror.",
                    "type": "integer"
                  },
                  "error": {
                    "description": "Only present for othererror and unexpectederror.",
                    "type": "string"
                  },
                  "from": {
                    "description": "Optional, and only present for autherror.",
                    "type": "string"
                  },
                  "name": {
                    "description": "httperror, networkerror, shutdownerror, etc.",
                    "type": "string"
                  }
                },
                "type": "object"
              },
              "status": {
                "description": "Internal sync status information. Omitted if it would be empty.",
                "properties": {
                  "service": {
                    "description": "The value of the Status.service property, unless it indicates success.",
                    "type": "string"
                  },
                  "sync": {
                    "description": "The value of the Status.sync property, unless it indicates success.",
                    "type": "string"
                  }
                },
                "type": "object"
              },
              "took": {
                "description": "duration in milliseconds",
                "type": "integer"
              },
              "when": {
                "description": "milliseconds since epoch",
                "type": "integer"
              },
              "why": {
                "description": "Optional, why the sync occurred, excluded if we don't know.",
                "type": "string"
              }
            },
            "type": "object"
          },
          "type": "array"
        },
        "uid": {
          "description": "Hashed FxA unique ID, or string of 32 zeros. If this changes between syncs, the payload is submitted.",
          "type": "string"
        },
        "version": {
          "maximum": 1,
          "minimum": 1,
          "type": "integer"
        },
        "why": {
          "description": "Why did we submit the ping?",
          "enum": [
            "idchange",
            "schedule",
            "shutdown"
          ],
          "type": "string"
        }
      },
      "type": "object"
    },
    "type": {
      "enum": [
        "sync"
      ],
      "type": "string"
    },
    "version": {
      "maximum": 4,
      "minimum": 4,
      "type": "number"
    }
  },
  "required": [
    "type",
    "id",
    "creationDate",
    "version",
    "application",
    "payload"
  ],
  "title": "sync",
  "type": "object"
}

=== crankycoder/mozilla-pipeline-schemas/validation/telemetry/sync.4.sample.pass.json
{
  "type": "sync",
  "id": "180bbc67-ed08-7846-a3d6-b82ada0b6f08",
  "creationDate": "2019-02-16T17:23:29.850Z",
  "version": 4,
  "application": {
    "architecture": "x86-64",
    "buildId": "20190213102848",
    "name": "Firefox",
    "version": "67.0a1",
    "displayVersion": "67.0a1",
    "vendor": "Mozilla",
    "platformVersion": "67.0a1",
    "xpcomAbi": "x86_64-gcc3",
    "channel": "nightly"
  },
  "payload": {
    "os": {
      "name": "Darwin",
      "version": "18.0.0",
      "locale": "en-CA"
    },
    "why": "schedule",
    "version": 1,
    "syncs": [
      {
        "when": 1550298047806,
        "took": 2077,
        "devices": [
          {
            "os": "Android",
            "version": "65.0.1",
            "id": "f38b5add46460b49c7373bac4c99f96bfda39af90ed01ce2b4b24957cd5bbeba"
          }
        ],
        "why": "schedule",
        "engines": [
          {
            "name": "clients",
            "took": 277
          },
          {
            "name": "tabs",
            "took": 6
          },
          {
            "name": "bookmarks",
            "took": 16
          },
          {
            "name": "forms",
            "took": 4
          },
          {
            "name": "history",
            "took": 394,
            "outgoing": [
              {
                "sent": 8
              }
            ]
          }
        ]
      },
      {
        "when": 1550301657882,
        "took": 2058,
        "devices": [
          {
            "os": "Android",
            "version": "65.0.1",
            "id": "f38b5add46460b49c7373bac4c99f96bfda39af90ed01ce2b4b24957cd5bbeba"
          }
        ],
        "why": "schedule",
        "engines": [
          {
            "name": "clients",
            "took": 624
          },
          {
            "name": "tabs",
            "took": 3
          },
          {
            "name": "bookmarks",
            "took": 12
          },
          {
            "name": "forms",
            "took": 5
          },
          {
            "name": "history",
            "took": 413,
            "outgoing": [
              {
                "sent": 8
              }
            ]
          }
        ]
      }
    ],
    "uid": "43720380d3e0935ca8d715b98d0da438",
    "deviceID": "0dd0695bf3753be0bf3de5f9809b145f68441b65bfeac85d89b31e04718bbaa6",
    "sessionStartDate": "2019-02-15T13:00:00.0-04:00",
    "histograms": {
      "PWMGR_BLOCKLIST_NUM_SITES": {
        "bucket_count": 10,
        "histogram_type": 0,
        "sum": 1,
        "range": [
          1,
          100
        ],
        "values": {
          "0": 0,
          "1": 1,
          "2": 0
        }
      },
      "PWMGR_NUM_SAVED_PASSWORDS": {
        "bucket_count": 50,
        "histogram_type": 0,
        "sum": 208,
        "range": [
          1,
          750
        ],
        "values": {
          "175": 0,
          "196": 1,
          "219": 0
        }
      }
    }
  }
}
